repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: check-case-conflict
    -   id: check-toml
    -   id: trailing-whitespace
    -   id: debug-statements
#    -   id: no-commit-to-branch  # no commit to main, master
#        args: ['--branch', 'main',]
    -   id: end-of-file-fixer
#    -   id: double-quote-string-fixer
    -   id: requirements-txt-fixer

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black

-   repo: https://github.com/dhruvmanila/remove-print-statements
    rev: 'v0.5.0'
    hooks:
    - id: remove-print-statements
      args: ['--verbose']   # Show all the print statements to be removed

-   repo: https://github.com/astral-sh/ruff-pre-commit
      # Ruff version.
    rev: v0.0.278
    hooks:
        - id: ruff
          args: [ --fix, --exit-non-zero-on-fix ]
